### PR TITLE
Upgrade cucumber-clojure to latest version.

### PR DESCRIPTION
**Pull request by punkisdead**
This upgrades the cucumber-clojure dependency to the latest version. The latest cucumber-clojure version includes some fixes to add tagged Before/After hooks in clojure.

### CODE REVIEW

**Comment by shaolang** [comment]
@punkisdead The upgraded version no longer outputs `test-reports/cucumber.out` in the project's target directory.

**Comment by punkisdead** [comment]
Sorry, I had removed that because it wouldn't compile as is, and must have forgotten to fix that.

**Comment by nilswloka** [comment]
Thanks for contributing. I'll have a look at the PR later this week. Do you think you could add a scenario that checks for output in `test-reports`?

**Comment by punkisdead** [comment]
I can certainly try.

**Comment by punkisdead** [comment]
I added a scenario now that verifies that it creates a `cucumber.out` file in `target/test-reports`

**Comment by punkisdead** [comment]
Any idea when this may get merged in?

**Comment by punkisdead** [comment]
:shipit:

**Pull request closed without merging**
